netty:
  port: 5566
  http_port: 12000
  file_port: 12001

mqtt:
  url: tcp://192.168.9.230:1883
  client-id: test
  username: test123


spring:
  application:
    name: thingsboard-gateway

  # Kafka配置
  kafka:
    bootstrap-servers: 192.168.3.143:9092
    producer:
      retries: 3
      acks: all
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      group-id: device-data-group
#      auto-offset-reset: earliest
#      enable-auto-commit: true

